version: "3.9"

services:
  uptimebot:
    deploy:
      resources:
        limits:
          memory: 128m
    image: ghcr.io/vbychkovskyi/uptimebot:latest
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      JDBC_URL: jdbc:postgresql://postgres:5432/uptime_bot
      QUARTZ_INITIALIZE_SCHEMA: NEVER
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 128m
    environment:
      POSTGRES_DB: uptime_bot
      POSTGRES_USER: uptime_bot
      POSTGRES_PASSWORD: uptime_bot
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    command: >
      postgres
      -c shared_buffers=16MB
      -c effective_cache_size=32MB
      -c work_mem=512kB
      -c maintenance_work_mem=8MB
      -c wal_buffers=1MB
      -c max_connections=10
      -c max_worker_processes=1
      -c max_parallel_workers=0
      -c max_parallel_workers_per_gather=0
      -c synchronous_commit=off
      -c fsync=off
      -c full_page_writes=off

volumes:
  postgres_data_prod:
